#
# Conditional build:
%bcond_without	apidocs		# API documentation
%bcond_without	ngram		# ARPA ngram language model
%bcond_without	static_libs	# static library
%bcond_with	xevie		# Xevie based gpresagemate app
#
Summary:	Presage - the intelligent predictive text entry system
Summary(pl.UTF-8):	Presage - inteligentny, przewidujący system wprowadzania tekstu
Name:		presage
Version:	0.9.1
Release:	4
License:	GPL v2+
Group:		Libraries
Source0:	http://downloads.sourceforge.net/presage/%{name}-%{version}.tar.gz
# Source0-md5:	9667be297912fa0d432e748526d8dd9e
Patch0:		%{name}-link.patch
Patch1:		%{name}-configure.patch
Patch2:		%{name}-build.patch
Patch3:		%{name}-cmuclmtk.patch
Patch4:		%{name}-c++17.patch
Patch5:		%{name}-format.patch
URL:		http://presage.sourceforge.net/
BuildRequires:	autoconf >= 2.50
BuildRequires:	automake >= 1:1.9
%{?with_ngram:BuildRequires:	cmuclmtk >= 0.7}
BuildRequires:	cppunit-devel >= 1.9.6
%{?with_apidocs:BuildRequires:	doxygen}
BuildRequires:	graphviz
BuildRequires:	glib2-devel >= 1:2.0
BuildRequires:	gtk+2-devel >= 1:2.0
BuildRequires:	help2man
BuildRequires:	libstdc++-devel
BuildRequires:	libtool >= 2:2
BuildRequires:	ncurses-devel
BuildRequires:	pkgconfig
BuildRequires:	python-devel >= 2.0
BuildRequires:	rpm-build >= 4.6
BuildRequires:	rpm-pythonprov
BuildRequires:	rpmbuild(macros) >= 1.714
BuildRequires:	sed >= 4.0
BuildRequires:	sqlite3-devel >= 3
BuildRequires:	swig-python >= 2.0
BuildRequires:	tinyxml-devel
BuildRequires:	xorg-lib-libX11-devel
%{?with_xevie:BuildRequires:	xorg-lib-libXevie-devel}
Requires:	%{name}-libs = %{version}-%{release}
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Presage (formerly known as Soothsayer) generates predictions by
modelling natural language as a combination of redundant information
sources. Presage computes probabilities for words which are most
likely to be entered next by merging predictions generated by the
different predictive algorithms. Presage's modular and extensible
architecture allows its language model to be extended and customized
to utilize statistical, syntactic, and semantic predictive algorithms.

%description -l pl.UTF-8
Presage (wcześniej znany jako Soothsayer) generuje przewidywania
poprzez modelowanie języka naturalnego jako kombinacji redundantnych
źródeł informacji. Presage wylicza prawdopodobieństwa słów, które są
najbardziej spodziewane być wpisane jako kolejne, łącząc przewidywania
wygenerowane różnymi algorytmami predykcji. Modularna i rozszerzalna
architektura Presage pozwala na rozszerzanie modelu języka i
dostosowywanie go, aby wykorzystywał algorytmy statystyczne,
syntaktyczne oraz semantyczne.

%package libs
Summary:	Presage shared library
Summary(pl.UTF-8):	Biblioteka współdzielona Presage
Group:		Libraries

%description libs
Presage shared library.

%description libs -l pl.UTF-8
Biblioteka współdzielona Presage.

%package devel
Summary:	Header files for Presage library
Summary(pl.UTF-8):	Pliki nagłówkowe biblioteki Presage
Group:		Development/Libraries
Requires:	%{name}-libs = %{version}-%{release}
Requires:	libstdc++-devel

%description devel
Header files for Presage library.

%description devel -l pl.UTF-8
Pliki nagłówkowe biblioteki Presage.

%package static
Summary:	Static Presage library
Summary(pl.UTF-8):	Statyczna biblioteka Presage
Group:		Development/Libraries
Requires:	%{name}-devel = %{version}-%{release}

%description static
Static Presage library.

%description static -l pl.UTF-8
Statyczna biblioteka Presage.

%package apidocs
Summary:	API documentation for Presage library
Summary(pl.UTF-8):	Dokumentacja API biblioteki Presage
Group:		Documentation
BuildArch:	noarch

%description apidocs
API documentation for Presage library.

%description apidocs -l pl.UTF-8
Dokumentacja API biblioteki Presage.

%package dbus
Summary:	Presage DBus service
Summary(pl.UTF-8):	Usługa DBus presage
Group:		Applications
Requires:	%{name} = %{version}-%{release}
Requires:	python-dbus
Requires:	python-presage = %{version}-%{release}
Requires:	python-pygobject >= 2.28

%description dbus
Presage is an intelligent predictive text entry system. This package
contains the presage D-Bus service.

%description dbus 
Presage to inteligentny, przewidujący system wprowadzania tekstu. Ten
pakiet zawiera usługę D-Bus presage.

%package gtk
Summary:	GTK+ presage applications
Summary(pl.UTF-8):	Aplikacje presage oparte na GTK+
Group:		X11/Applications
Requires:	%{name} = %{version}-%{release}

%description gtk
GTK+ presage applications:
%if %{with xevie}
- gpresagemate: user input predictions using XEvIE extension
%endif
- gprompter: intelligent predictive GTK+ text editor

%description gtk -l pl.UTF-8
Aplikacje presage oparte na GTK+:
%if %{with xevie}
- gpresagemate - przewidywanie wejścia użytkownika z wykorzystaniem
  rozszerzenia XEvIE
%endif
- gprompter - inteligenty, przewidujący edytor tekstu oparty na GTK+

%package -n python-presage
Summary:	Python binding for presage
Summary(pl.UTF-8):	Wiązanie Pythona do presage
Group:		Libraries/Python
Requires:	%{name}-libs = %{version}-%{release}

%description -n python-presage
Python binding for presage, the intelligent predictive text entry
system.

%description -n python-presage -l pl.UTF-8
Wiązanie Pythona do presage - inteligentnego, przewidującego systemu
wprowadzania tekstu.

%package -n python-pypresagemate
Summary:	Python presagemate widget
Summary(pl.UTF-8):	Widget presagemate dla Pythona
Group:		Libraries/Python
Requires:	python-Xlib
Requires:	python-presage = %{version}-%{release}
Requires:	python-pyatspi
Requires:	python-pygtk-gtk >= 2:2
Requires:	python-pygtk-pango >= 2:2

%description -n python-pypresagemate
Python presagemate widget.

%description -n python-pypresagemate -l pl.UTF-8
Widget presagemate dla Pythona.

%package -n python-pyprompter
Summary:	pyprompter - intelligent predictive wxPython text editor
Summary(pl.UTF-8):	pyprompter - inteligentny, przewidujący edytor tekstu wykorzystujący bibliotekę wxPython
Group:		Libraries/Python
Requires:	python-wxPython

%description -n python-pyprompter
pyprompter is an intelligent predictive wxPython text editor.

%description -n python-pyprompter -l pl.UTF-8
pyprompter to inteligentny, przewidujący edytor tekstu wykorzystujący
bibliotekę wxPython.

%prep
%setup -q
%patch -P0 -p1
%patch -P1 -p1
%patch -P2 -p1
%patch -P3 -p1
%patch -P4 -p1
%patch -P5 -p1

%{__sed} -i -e '1s,/usr/bin/env python,%{__python},' \
	apps/dbus/{presage_dbus_python_demo.in,presage_dbus_service,presage_dbus_service.py}
%{__sed} -i -e '1s,/usr/bin/python$,%{__python},' \
	apps/python/pypresagemate.in

%build
%{__libtoolize}
%{__aclocal} -I m4
%{__autoconf}
%{__autoheader}
%{__automake}
%configure \
	PYTHON=%{__python} \
	%{!?with_apidocs:--disable-documentation} \
	%{!?with_xevie:--disable-gpresagemate} \
	%{!?with_static_libs:--disable-static}
%{__make}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

%py_comp $RPM_BUILD_ROOT%{py_sitedir}
%py_ocomp $RPM_BUILD_ROOT%{py_sitedir}
%py_postclean

# not used
%{__rm} $RPM_BUILD_ROOT%{_datadir}/%{name}/presage.{svg,xpm}
# packaged as %doc
%{__rm} -r $RPM_BUILD_ROOT%{_datadir}/%{name}/html
%{__rm} $RPM_BUILD_ROOT%{_datadir}/%{name}/{getting_started,python_binding}.txt

%clean
rm -rf $RPM_BUILD_ROOT

%post	libs -p /sbin/ldconfig
%postun	libs -p /sbin/ldconfig

%files
%defattr(644,root,root,755)
%doc AUTHORS ChangeLog FAQ NEWS README THANKS TODO doc/getting_started.txt
%config(noreplace) %verify(not md5 mtime size) %{_sysconfdir}/presage.xml
%attr(755,root,root) %{_bindir}/presage_demo
%attr(755,root,root) %{_bindir}/presage_demo_text
%attr(755,root,root) %{_bindir}/presage_python_demo
%attr(755,root,root) %{_bindir}/presage_simulator
%attr(755,root,root) %{_bindir}/text2ngram
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/abbreviations_*.txt
%if %{with ngram}
%{_datadir}/%{name}/arpa_en.arpa
%{_datadir}/%{name}/arpa_en.vocab
%{_datadir}/%{name}/arpa_it.arpa
%{_datadir}/%{name}/arpa_it.vocab
%endif
%{_datadir}/%{name}/database_*.db
%{_datadir}/%{name}/presage.png
%{_mandir}/man1/presage_demo.1*
%{_mandir}/man1/presage_demo_text.1*
%{_mandir}/man1/presage_python_demo.1*
%{_mandir}/man1/presage_simulator.1*
%{_mandir}/man1/text2ngram.1*

%files libs
%defattr(644,root,root,755)
%attr(755,root,root) %{_libdir}/libpresage.so.*.*.*
%attr(755,root,root) %ghost %{_libdir}/libpresage.so.1

%files devel
%defattr(644,root,root,755)
%attr(755,root,root) %{_libdir}/libpresage.so
%{_libdir}/libpresage.la
%{_includedir}/presage*.h

%if %{with static_libs}
%files static
%defattr(644,root,root,755)
%{_libdir}/libpresage.a
%endif

%if %{with apidocs}
%files apidocs
%defattr(644,root,root,755)
%doc doc/html/*.{css,html,js,png}
%endif

%files dbus
%defattr(644,root,root,755)
# dbus service, R: python-dbus
%attr(755,root,root) %{_bindir}/presage_dbus_python_demo
%attr(755,root,root) %{_bindir}/presage_dbus_service
%{py_sitescriptdir}/presage_dbus_service.py[co]
%{_datadir}/dbus-1/services/org.gnome.presage.service
%{_mandir}/man1/presage_dbus_python_demo.1*
%{_mandir}/man1/presage_dbus_service.1*

%files gtk
%defattr(644,root,root,755)
%if %{with xevie}
%attr(755,root,root) %{_bindir}/gpresagemate
%endif
%attr(755,root,root) %{_bindir}/gprompter
%{_desktopdir}/gprompter.desktop
%{_iconsdir}/hicolor/scalable/apps/gprompter.svg
%{_pixmapsdir}/gprompter.png
%{_pixmapsdir}/gprompter.xpm
%{_mandir}/man1/gprompter.1*

%files -n python-presage
%defattr(644,root,root,755)
%doc doc/python_binding.txt
%attr(755,root,root) %{py_sitedir}/_presage.so
%{py_sitedir}/presage.py[co]
%{py_sitedir}/python_presage-%{version}-py*.egg-info

%files -n python-pypresagemate
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/pypresagemate
%{py_sitescriptdir}/presagemate

%files -n python-pyprompter
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/pyprompter
%{py_sitedir}/prompter
%{py_sitedir}/pyprompter-%{version}-py*.egg-info
%{_desktopdir}/pyprompter.desktop
%{_iconsdir}/hicolor/scalable/apps/pyprompter.svg
%{_pixmapsdir}/pyprompter.png
%{_pixmapsdir}/pyprompter.xpm
%{_mandir}/man1/pyprompter.1*
